version: "3.7"

networks:
  docunder-network:
    driver: bridge

volumes:
  users-postgres:

services:
          postgres:
                  image: postgres:16.2-alpine3.19
                  container_name: docunder-db
                  restart: always
                  shm_size: 128mb
                  volumes:
                    - "users-postgres:/var/lib/postgresql/data"
                  networks:
                    - docunder-network
                  environment:
                    POSTGRES_USER: ${POSTGRES_USER}
                    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                    POSTGRES_DB: ${POSTGRES_DB}
                  ports:
                    - 5432:5432
                    
          backend:
                  build:
                      context: "./"
                      dockerfile: Dockerfile.prod
                  container_name: docunder-backend
                  restart: always
                  networks:
                    - docunder-network
                  ports:
                    - 3000:3000
                  depends_on:
                    - postgres
                  
                    

                          
                    
