FROM node:20.11.1-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY src/prisma ./prisma/

ENV NODE_ENV=development
RUN npm install

COPY . .
RUN npm run build

FROM node:20.11.1-alpine AS dev

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

CMD ["npm", "run", "start:migrate:dev"]