version: "3.7"

networks:
  app-network:
    driver: bridge

volumes:
  users-postgres:

services:
          usersdb:
                  image: postgres
                  container_name: db-users
                  restart: always
                  volumes:
                    - "users-postgres:/data/db"
                  networks:
                    - "app-network"
                  environment:
                    POSTGRES_PASSWORD: 
                    POSTGRES_USER: 
                  ports:
                    - "8080:8080"
                    
          app:
                  build:
                      context: "./"
                      dockerfile: dockerfile-app
                  container_name: app
                  restart: always
                  networks:
                    - "app-network"
                  ports:
                    - "3000:3000"
                  depends_on:
                    - "usersdb"
                  
                    

                          
                    
