version: "3.7"

networks:
  app-network:
    driver: bridge

volumes:
  users-postgres:

services:
          usersdb:
                  image: postgres:16.2
                  container_name: db-users
                  restart: always
                  shm_size: 128mb
                  volumes:
                    - "users-postgres:/var/lib/postgresql/data"
                    - "./sql:/docker-entrypoint-initdb.d"
                  networks:
                    - "app-network"
                  environment:
                    POSTGRES_USER: ${POSTGRES_USER}
                    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                    POSTGRES_DB: ${POSTGRES_DB}
                  env_file:
                    - .env
                  ports:
                    - "5432:5432"
                    
          app:
                  build:
                      context: "./"
                      dockerfile: dockerfile-app
                  container_name: app
                  restart: always
                  networks:
                    - "app-network"
                  ports:
                    - "3000:3000"
                  depends_on:
                    - "usersdb"
                  
                    

                          
                    
